# All 50 skills × 4 levels from 主要玩法.md
# Each skill level: {name, level, category, cooldown, damage, effects, range_desc, effect_desc}
# cooldown: seconds (0 = passive, -1 = unknown/TBD)
# effects: list of dicts with keys: type, value, duration, etc.

SKILLS = {
    # ---- 进攻类 (Offensive) ----
    "火焰": [
        {"name": "火焰", "level": 1, "category": "offensive", "cooldown": 8,
         "damage": 20, "range_desc": "20m直线, 爆炸2m",
         "effects": [], "desc": "发射小火球，造成20点伤害。"},
        {"name": "火焰", "level": 2, "category": "offensive", "cooldown": 8,
         "damage": 35, "range_desc": "22m直线, 爆炸2.5m",
         "effects": [{"type": "burn", "dps": 5, "duration": 2}],
         "desc": "造成35点伤害，附带2秒燃烧（每秒5点）。"},
        {"name": "火焰", "level": 3, "category": "offensive", "cooldown": 8,
         "damage": 50, "range_desc": "24m直线, 爆炸3m",
         "effects": [{"type": "burn", "dps": 8, "duration": 3}],
         "desc": "造成50点伤害，燃烧3秒（每秒8点）。"},
        {"name": "火焰", "level": 4, "category": "offensive", "cooldown": 8,
         "damage": 70, "range_desc": "26m直线, 爆炸3.5m",
         "effects": [{"type": "burn", "dps": 10, "duration": 4},
                     {"type": "extra_damage_center", "value": 20}],
         "desc": "造成70点伤害，燃烧4秒（每秒10点），爆炸中心额外20点。"},
    ],
    "冰霜箭": [
        {"name": "冰霜箭", "level": 1, "category": "offensive", "cooldown": 6,
         "damage": 15, "range_desc": "25m直线",
         "effects": [{"type": "slow", "value": 30, "duration": 1.5}],
         "desc": "射出一支冰箭，造成15点伤害，减速30%持续1.5秒。"},
        {"name": "冰霜箭", "level": 2, "category": "offensive", "cooldown": 6,
         "damage": 25, "range_desc": "27m直线",
         "effects": [{"type": "slow", "value": 50, "duration": 2}],
         "desc": "造成25点伤害，减速50%持续2秒。"},
        {"name": "冰霜箭", "level": 3, "category": "offensive", "cooldown": 6,
         "damage": 35, "range_desc": "29m直线",
         "effects": [{"type": "slow", "value": 60, "duration": 2.5},
                     {"type": "freeze", "duration": 0.5}],
         "desc": "造成35点伤害，减速60%持续2.5秒，冰冻0.5秒。"},
        {"name": "冰霜箭", "level": 4, "category": "offensive", "cooldown": 6,
         "damage": 50, "range_desc": "32m直线",
         "effects": [{"type": "freeze", "duration": 1},
                     {"type": "slow", "value": 60, "duration": 2},
                     {"type": "vuln", "value": 10, "duration": 3}],
         "desc": "造成50点伤害，冰冻1秒，减速60%持续2秒，命中后目标受到伤害增加10%持续3秒。"},
    ],
    "雷电击": [
        {"name": "雷电击", "level": 1, "category": "offensive", "cooldown": 7,
         "damage": 25, "range_desc": "15m单体, 弹跳5m",
         "effects": [], "desc": "召唤一道闪电，造成25点伤害。"},
        {"name": "雷电击", "level": 2, "category": "offensive", "cooldown": 7,
         "damage": 40, "range_desc": "18m单体, 弹跳6m",
         "effects": [{"type": "chain", "targets": 1, "chain_damage": 25}],
         "desc": "闪电弹跳1次，首目标40点，第二目标25点。"},
        {"name": "雷电击", "level": 3, "category": "offensive", "cooldown": 7,
         "damage": 55, "range_desc": "20m单体, 弹跳7m",
         "effects": [{"type": "chain", "targets": 2, "chain_damage": [40, 30]}],
         "desc": "弹跳2次，首目标55点，第二目标40点，第三目标30点。"},
        {"name": "雷电击", "level": 4, "category": "offensive", "cooldown": 7,
         "damage": 70, "range_desc": "22m单体, 弹跳8m",
         "effects": [{"type": "chain", "targets": 3, "chain_damage": [55, 40, 30]},
                     {"type": "stun", "duration": 0.2, "per_chain": True}],
         "desc": "弹跳3次，首目标70点，依次55/40/30点，每次弹跳眩晕0.2秒。"},
    ],
    "风刃": [
        {"name": "风刃", "level": 1, "category": "offensive", "cooldown": 5,
         "damage": 20, "range_desc": "15m直线, 宽1.5m",
         "effects": [{"type": "pierce", "count": 1}],
         "desc": "向前发出一道风刃，造成20点伤害，穿透1个敌人。"},
        {"name": "风刃", "level": 2, "category": "offensive", "cooldown": 5,
         "damage": 30, "range_desc": "18m直线, 宽2m",
         "effects": [{"type": "pierce", "count": 2}],
         "desc": "造成30点伤害，穿透2个敌人。"},
        {"name": "风刃", "level": 3, "category": "offensive", "cooldown": 5,
         "damage": 40, "range_desc": "20m直线, 宽2.5m",
         "effects": [{"type": "pierce", "count": 3},
                     {"type": "damage_falloff", "per_pierce": 20}],
         "desc": "造成40点伤害，穿透3个敌人，穿透后伤害衰减20%。"},
        {"name": "风刃", "level": 4, "category": "offensive", "cooldown": 5,
         "damage": 55, "range_desc": "22m直线, 宽3m",
         "effects": [{"type": "pierce", "count": 999},
                     {"type": "slow", "value": 20, "duration": 1.5}],
         "desc": "造成55点伤害，穿透所有敌人，命中后敌人减速20%持续1.5秒。"},
    ],
    "暗影突袭": [
        {"name": "暗影突袭", "level": 1, "category": "offensive", "cooldown": 10,
         "damage": 25, "range_desc": "12m瞬移",
         "effects": [], "desc": "瞬移至目标背后，造成25点伤害。"},
        {"name": "暗影突袭", "level": 2, "category": "offensive", "cooldown": 10,
         "damage": 40, "range_desc": "14m瞬移",
         "effects": [{"type": "stealth", "duration": 2}],
         "desc": "造成40点伤害，获得2秒隐身。"},
        {"name": "暗影突袭", "level": 3, "category": "offensive", "cooldown": 10,
         "damage": 55, "range_desc": "16m瞬移",
         "effects": [{"type": "stealth", "duration": 3},
                     {"type": "speed_boost", "value": 15, "duration": 3}],
         "desc": "造成55点伤害，隐身3秒，隐身期间移速提升15%。"},
        {"name": "暗影突袭", "level": 4, "category": "offensive", "cooldown": 10,
         "damage": 75, "range_desc": "18m瞬移",
         "effects": [{"type": "stealth", "duration": 4},
                     {"type": "speed_boost", "value": 25, "duration": 4},
                     {"type": "silence", "duration": 1}],
         "desc": "造成75点伤害，隐身4秒，移速提升25%，瞬移后目标被沉默1秒。"},
    ],
    "圣光斩": [
        {"name": "圣光斩", "level": 1, "category": "offensive", "cooldown": 6,
         "damage": 20, "range_desc": "前方4m扇形",
         "effects": [{"type": "execute_bonus", "threshold": 30, "bonus": 10}],
         "desc": "挥出一道圣光，造成20点伤害，对生命值低于30%的敌人额外10点。"},
        {"name": "圣光斩", "level": 2, "category": "offensive", "cooldown": 6,
         "damage": 35, "range_desc": "前方5m扇形",
         "effects": [{"type": "execute_bonus", "threshold": 30, "bonus": 20},
                     {"type": "blind", "duration": 1}],
         "desc": "造成35点伤害，对低生命敌人额外20点，附带1秒致盲。"},
        {"name": "圣光斩", "level": 3, "category": "offensive", "cooldown": 6,
         "damage": 50, "range_desc": "前方6m扇形",
         "effects": [{"type": "execute_bonus", "threshold": 30, "bonus": 30},
                     {"type": "blind", "duration": 1.5},
                     {"type": "self_armor", "value": 10, "duration": 3}],
         "desc": "造成50点伤害，对低生命敌人额外30点，致盲1.5秒，自身获得10点护甲3秒。"},
        {"name": "圣光斩", "level": 4, "category": "offensive", "cooldown": 6,
         "damage": 70, "range_desc": "前方7m扇形",
         "effects": [{"type": "execute_bonus", "threshold": 30, "bonus": 40},
                     {"type": "blind", "duration": 2},
                     {"type": "self_armor", "value": 20, "duration": 4},
                     {"type": "self_dmg_reduction", "value": 10, "duration": 4}],
         "desc": "造成70点伤害，对低生命敌人额外40点，致盲2秒，自身获得20点护甲和10%减伤持续4秒。"},
    ],
    "剧毒飞镖": [
        {"name": "剧毒飞镖", "level": 1, "category": "offensive", "cooldown": 4,
         "damage": 10, "range_desc": "20m直线",
         "effects": [{"type": "poison", "dps": 5, "duration": 5}],
         "desc": "投掷毒镖，造成10点伤害，中毒5秒（每秒5点）。"},
        {"name": "剧毒飞镖", "level": 2, "category": "offensive", "cooldown": 4,
         "damage": 15, "range_desc": "22m直线",
         "effects": [{"type": "poison", "dps": 10, "duration": 5}],
         "desc": "造成15点伤害，中毒每秒10点，持续5秒。"},
        {"name": "剧毒飞镖", "level": 3, "category": "offensive", "cooldown": 4,
         "damage": 20, "range_desc": "24m直线",
         "effects": [{"type": "poison", "dps": 12, "duration": 5},
                     {"type": "heal_reduction", "value": 30, "duration": 5}],
         "desc": "造成20点伤害，中毒每秒12点，持续5秒，中毒期间治疗效果降低30%。"},
        {"name": "剧毒飞镖", "level": 4, "category": "offensive", "cooldown": 4,
         "damage": 30, "range_desc": "26m直线",
         "effects": [{"type": "poison", "dps": 15, "duration": 6},
                     {"type": "heal_reduction", "value": 50, "duration": 6},
                     {"type": "poison_burst", "value": 30}],
         "desc": "造成30点伤害，中毒每秒15点，持续6秒，治疗效果降低50%，中毒结束时造成30点爆发伤害。"},
    ],
    "爆破弹": [
        {"name": "爆破弹", "level": 1, "category": "offensive", "cooldown": 6,
         "damage": 30, "range_desc": "22m直线, 爆炸2m",
         "effects": [], "desc": "发射一颗爆破弹，命中造成30点范围伤害。"},
        {"name": "爆破弹", "level": 2, "category": "offensive", "cooldown": 6,
         "damage": 45, "range_desc": "24m直线, 爆炸3m",
         "effects": [], "desc": "造成45点范围伤害。"},
        {"name": "爆破弹", "level": 3, "category": "offensive", "cooldown": 6,
         "damage": 60, "range_desc": "26m直线, 爆炸3.5m",
         "effects": [{"type": "burn_zone", "dps": 15, "duration": 2}],
         "desc": "造成60点范围伤害，爆炸后留下燃烧区域2秒，每秒15点伤害。"},
        {"name": "爆破弹", "level": 4, "category": "offensive", "cooldown": 6,
         "damage": 80, "range_desc": "28m直线, 爆炸4m",
         "effects": [{"type": "burn_zone", "dps": 20, "duration": 3},
                     {"type": "extra_damage_center", "value": 25}],
         "desc": "造成80点范围伤害，燃烧区域3秒，每秒20点伤害，爆炸中心额外25点。"},
    ],
    "回旋镖": [
        {"name": "回旋镖", "level": 1, "category": "offensive", "cooldown": 5,
         "damage": 15, "range_desc": "投掷12m",
         "effects": [{"type": "return_damage", "value": 10}],
         "desc": "投出回旋镖，去程15点，回程10点。"},
        {"name": "回旋镖", "level": 2, "category": "offensive", "cooldown": 5,
         "damage": 25, "range_desc": "投掷14m",
         "effects": [{"type": "return_damage", "value": 20}],
         "desc": "去程25点，回程20点。"},
        {"name": "回旋镖", "level": 3, "category": "offensive", "cooldown": 5,
         "damage": 35, "range_desc": "投掷16m",
         "effects": [{"type": "return_damage", "value": 30},
                     {"type": "pierce", "count": 1, "return_only": True}],
         "desc": "去程35点，回程30点，可穿透1个敌人。"},
        {"name": "回旋镖", "level": 4, "category": "offensive", "cooldown": 5,
         "damage": 50, "range_desc": "投掷18m",
         "effects": [{"type": "return_damage", "value": 40},
                     {"type": "pierce", "count": 2},
                     {"type": "slow", "value": 20, "duration": 1}],
         "desc": "去程50点，回程40点，穿透2个敌人，命中后敌人减速20%持续1秒。"},
    ],
    "能量脉冲": [
        {"name": "能量脉冲", "level": 1, "category": "offensive", "cooldown": 7,
         "damage": 15, "range_desc": "自身周围4m圆形",
         "effects": [{"type": "knockback", "distance": 1}],
         "desc": "释放脉冲，对周围敌人造成15点伤害，击退小距离。"},
        {"name": "能量脉冲", "level": 2, "category": "offensive", "cooldown": 7,
         "damage": 25, "range_desc": "自身周围5m圆形",
         "effects": [{"type": "knockback", "distance": 2}],
         "desc": "造成25点伤害，击退距离增加。"},
        {"name": "能量脉冲", "level": 3, "category": "offensive", "cooldown": 7,
         "damage": 35, "range_desc": "自身周围6m圆形",
         "effects": [{"type": "knockback", "distance": 3},
                     {"type": "self_speed_boost", "value": 20, "duration": 2}],
         "desc": "造成35点伤害，击退距离增加，脉冲后获得20%加速持续2秒。"},
        {"name": "能量脉冲", "level": 4, "category": "offensive", "cooldown": 7,
         "damage": 50, "range_desc": "自身周围7m圆形",
         "effects": [{"type": "knockback", "distance": 5},
                     {"type": "self_speed_boost", "value": 30, "duration": 3},
                     {"type": "stun", "duration": 0.3}],
         "desc": "造成50点伤害，击退距离大幅增加，加速30%持续3秒，并附加0.3秒眩晕。"},
    ],
    # ---- 防守类 (Defensive) ----
    "冰甲术": [
        {"name": "冰甲术", "level": 1, "category": "defensive", "cooldown": 12,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "armor", "value": 10, "duration": 5},
                     {"type": "melee_slow_on_hit", "value": 20}],
         "desc": "获得10点护甲，持续5秒，近战攻击者被减速20%。"},
        {"name": "冰甲术", "level": 2, "category": "defensive", "cooldown": 12,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "armor", "value": 20, "duration": 6},
                     {"type": "melee_slow_on_hit", "value": 30}],
         "desc": "护甲20点，减速30%，持续6秒。"},
        {"name": "冰甲术", "level": 3, "category": "defensive", "cooldown": 12,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "armor", "value": 30, "duration": 7},
                     {"type": "melee_slow_on_hit", "value": 40},
                     {"type": "burst_on_break", "damage": 30, "radius": 3}],
         "desc": "护甲30点，减速40%，持续7秒，护甲破碎时造成周围冰霜伤害30点。"},
        {"name": "冰甲术", "level": 4, "category": "defensive", "cooldown": 12,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "armor", "value": 45, "duration": 8},
                     {"type": "melee_slow_on_hit", "value": 50},
                     {"type": "burst_on_break", "damage": 50, "radius": 3},
                     {"type": "freeze_on_break", "duration": 0.5}],
         "desc": "护甲45点，减速50%，持续8秒，破碎时造成50点范围伤害，并冰冻周围敌人0.5秒。"},
    ],
    "圣盾术": [
        {"name": "圣盾术", "level": 1, "category": "defensive", "cooldown": 14,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "shield", "value": 30, "duration": 4}],
         "desc": "获得一个吸收30点伤害的护盾，持续4秒。"},
        {"name": "圣盾术", "level": 2, "category": "defensive", "cooldown": 14,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "shield", "value": 60, "duration": 5}],
         "desc": "吸收60点伤害，持续5秒。"},
        {"name": "圣盾术", "level": 3, "category": "defensive", "cooldown": 14,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "shield", "value": 90, "duration": 6},
                     {"type": "heal_on_break", "value": 20}],
         "desc": "吸收90点伤害，持续6秒，护盾破碎时回复20点生命。"},
        {"name": "圣盾术", "level": 4, "category": "defensive", "cooldown": 14,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "shield", "value": 120, "duration": 7},
                     {"type": "heal_on_break", "value": 40},
                     {"type": "cc_immunity", "duration": 7}],
         "desc": "吸收120点伤害，持续7秒，护盾破碎时回复40点生命，持续期间免疫控制。"},
    ],
    "闪避步": [
        {"name": "闪避步", "level": 1, "category": "defensive", "cooldown": 14,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "dodge", "duration": 1}],
         "desc": "使用后1秒内闪避所有攻击。"},
        {"name": "闪避步", "level": 2, "category": "defensive", "cooldown": 14,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "dodge", "duration": 1.5},
                     {"type": "speed_boost", "value": 20, "duration": 1.5}],
         "desc": "闪避时间1.5秒，移动速度提升20%。"},
        {"name": "闪避步", "level": 3, "category": "defensive", "cooldown": 14,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "dodge", "duration": 1.75},
                     {"type": "speed_boost", "value": 25, "duration": 1.75},
                     {"type": "cd_reduction_on_dodge", "value": 1}],
         "desc": "闪避时间1.75秒，移速提升25%，闪避成功减少其他技能冷却1秒。"},
        {"name": "闪避步", "level": 4, "category": "defensive", "cooldown": 14,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "dodge", "duration": 2},
                     {"type": "speed_boost", "value": 30, "duration": 2},
                     {"type": "next_attack_crit"},
                     {"type": "dmg_reduction", "value": 10, "duration": 2}],
         "desc": "闪避时间2秒，移速提升30%，成功闪避后下一次攻击必暴击，闪避期间获得10%减伤。"},
    ],
    "荆棘之甲": [
        {"name": "荆棘之甲", "level": 1, "category": "defensive", "cooldown": 15,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "armor", "value": 5, "duration": 999},
                     {"type": "reflect_melee", "value": 10}],
         "desc": "获得5点护甲，反弹10%近战伤害。"},
        {"name": "荆棘之甲", "level": 2, "category": "defensive", "cooldown": 15,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "armor", "value": 10, "duration": 999},
                     {"type": "reflect_melee", "value": 15}],
         "desc": "护甲10点，反弹15%。"},
        {"name": "荆棘之甲", "level": 3, "category": "defensive", "cooldown": 15,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "armor", "value": 15, "duration": 999},
                     {"type": "reflect_melee", "value": 20},
                     {"type": "reflect_slow", "duration": 1}],
         "desc": "护甲15点，反弹20%，且反弹伤害附带1秒减速。"},
        {"name": "荆棘之甲", "level": 4, "category": "defensive", "cooldown": 15,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "armor", "value": 25, "duration": 999},
                     {"type": "reflect_melee", "value": 25},
                     {"type": "reflect_slow", "duration": 1},
                     {"type": "active_double_reflect", "duration": 3},
                     {"type": "dmg_reduction_active", "value": 10, "duration": 3}],
         "desc": "护甲25点，反弹25%，主动激活后反弹效果加倍3秒，激活期间额外减伤10%。"},
    ],
    "土墙术": [
        {"name": "土墙术", "level": 1, "category": "defensive", "cooldown": 12,
         "damage": 0, "range_desc": "墙长4m, 放置15m",
         "effects": [{"type": "wall", "length": 4, "duration": 3, "hp": 100}],
         "desc": "召唤一堵小土墙，阻挡移动和投射物，持续3秒。"},
        {"name": "土墙术", "level": 2, "category": "defensive", "cooldown": 12,
         "damage": 0, "range_desc": "墙长5m, 放置18m",
         "effects": [{"type": "wall", "length": 5, "duration": 4, "hp": 150}],
         "desc": "土墙更大更厚，持续4秒。"},
        {"name": "土墙术", "level": 3, "category": "defensive", "cooldown": 12,
         "damage": 0, "range_desc": "墙长5m, 放置20m",
         "effects": [{"type": "wall", "length": 5, "duration": 5, "hp": 225}],
         "desc": "持续5秒，墙体生命值增加50%。"},
        {"name": "土墙术", "level": 4, "category": "defensive", "cooldown": 12,
         "damage": 0, "range_desc": "墙长6m, 放置22m",
         "effects": [{"type": "wall", "length": 6, "duration": 6, "hp": 400},
                     {"type": "nearby_ally_armor", "value": 10}],
         "desc": "持续6秒，墙体生命值翻倍，墙体存在期间为周围友军提供10点护甲。"},
    ],
    "法术反射": [
        {"name": "法术反射", "level": 1, "category": "defensive", "cooldown": 15,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "reflect_spell", "duration": 1, "directed_only": True}],
         "desc": "1秒内反射下一个指向性技能。"},
        {"name": "法术反射", "level": 2, "category": "defensive", "cooldown": 15,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "reflect_spell", "duration": 1.5}],
         "desc": "反射时间1.5秒，可反射非指向性。"},
        {"name": "法术反射", "level": 3, "category": "defensive", "cooldown": 15,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "reflect_spell", "duration": 2},
                     {"type": "heal_on_reflect", "value_pct": 10}],
         "desc": "反射时间2秒，反射后回复10%生命。"},
        {"name": "法术反射", "level": 4, "category": "defensive", "cooldown": 15,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "reflect_spell", "duration": 2.5},
                     {"type": "heal_on_reflect", "value_pct": 20},
                     {"type": "cd_refresh_on_reflect"}],
         "desc": "反射时间2.5秒，反射后回复20%生命，反射成功刷新冷却。"},
    ],
    "生命链接": [
        {"name": "生命链接", "level": 1, "category": "defensive", "cooldown": 20,
         "damage": 0, "range_desc": "链接距离10m",
         "effects": [{"type": "link", "share_pct": 20, "targets": 1}],
         "desc": "与一名队友链接，双方分担20%受伤害。"},
        {"name": "生命链接", "level": 2, "category": "defensive", "cooldown": 20,
         "damage": 0, "range_desc": "链接距离12m",
         "effects": [{"type": "link", "share_pct": 30, "targets": 1},
                     {"type": "link_regen", "dps": -5}],
         "desc": "分担30%，且链接期间双方每秒回复5点生命。"},
        {"name": "生命链接", "level": 3, "category": "defensive", "cooldown": 20,
         "damage": 0, "range_desc": "链接距离15m",
         "effects": [{"type": "link", "share_pct": 35, "targets": 2},
                     {"type": "link_regen", "dps": -8}],
         "desc": "分担35%，每秒回复8点生命，可链接两名队友。"},
        {"name": "生命链接", "level": 4, "category": "defensive", "cooldown": 20,
         "damage": 0, "range_desc": "链接距离18m",
         "effects": [{"type": "link", "share_pct": 40, "targets": 2},
                     {"type": "link_regen", "dps": -10},
                     {"type": "link_share_hp_on_death"}],
         "desc": "分担40%，每秒回复10点生命，可链接两名队友，一方生命归零时另一方可选择平分生命值。"},
    ],
    "金身": [
        {"name": "金身", "level": 1, "category": "defensive", "cooldown": 20,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "invulnerable", "duration": 1.5, "immobile": True}],
         "desc": "进入无敌但无法行动，持续1.5秒。"},
        {"name": "金身", "level": 2, "category": "defensive", "cooldown": 20,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "invulnerable", "duration": 2, "immobile": True},
                     {"type": "heal_on_end", "value": 10}],
         "desc": "持续2秒，结束时回复10点生命。"},
        {"name": "金身", "level": 3, "category": "defensive", "cooldown": 20,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "invulnerable", "duration": 2.5, "immobile": True},
                     {"type": "heal_on_end", "value": 15},
                     {"type": "burst_on_end", "damage": 30, "radius": 3}],
         "desc": "持续2.5秒，结束时回复15点生命，对周围造成30点伤害。"},
        {"name": "金身", "level": 4, "category": "defensive", "cooldown": 20,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "invulnerable", "duration": 3, "immobile": True, "cancelable": True},
                     {"type": "heal_on_cancel", "value": 20},
                     {"type": "speed_on_cancel", "value": 20, "duration": 2}],
         "desc": "持续3秒，可提前取消，取消时回复20点生命并加速20%持续2秒。"},
    ],
    "韧性皮肤": [
        {"name": "韧性皮肤", "level": 1, "category": "defensive", "cooldown": 0,
         "damage": 0, "range_desc": "仅自身 (被动)",
         "effects": [{"type": "passive_dmg_reduction", "value": 5}],
         "desc": "被动减少5%所受伤害。"},
        {"name": "韧性皮肤", "level": 2, "category": "defensive", "cooldown": 0,
         "damage": 0, "range_desc": "仅自身 (被动)",
         "effects": [{"type": "passive_dmg_reduction", "value": 10},
                     {"type": "cc_reduction", "value": 20}],
         "desc": "减少10%，受到控制时间缩短20%。"},
        {"name": "韧性皮肤", "level": 3, "category": "defensive", "cooldown": 0,
         "damage": 0, "range_desc": "仅自身 (被动)",
         "effects": [{"type": "passive_dmg_reduction", "value": 15},
                     {"type": "cc_reduction", "value": 30},
                     {"type": "low_hp_dmg_reduction", "value": 10, "threshold": 30}],
         "desc": "减少15%，控制时间缩短30%，生命低于30%时额外减少10%。"},
        {"name": "韧性皮肤", "level": 4, "category": "defensive", "cooldown": 30,
         "damage": 0, "range_desc": "仅自身 (被动, 免疫控制内置CD30秒)",
         "effects": [{"type": "passive_dmg_reduction", "value": 20},
                     {"type": "cc_reduction", "value": 40},
                     {"type": "low_hp_dmg_reduction", "value": 15, "threshold": 30},
                     {"type": "cc_immune_once", "cd": 30}],
         "desc": "减少20%，控制时间缩短40%，生命低于30%时额外减少15%，每30秒免疫一次控制。"},
    ],
    "吸魂盾": [
        {"name": "吸魂盾", "level": 1, "category": "defensive", "cooldown": 14,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "absorb_and_heal", "heal_pct": 30}],
         "desc": "开启后吸收下一次攻击的伤害，回复吸收量30%的生命。"},
        {"name": "吸魂盾", "level": 2, "category": "defensive", "cooldown": 14,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "absorb_and_heal", "heal_pct": 50}],
         "desc": "回复50%吸收量。"},
        {"name": "吸魂盾", "level": 3, "category": "defensive", "cooldown": 14,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "absorb_and_heal", "heal_pct": 70},
                     {"type": "shield_after_absorb", "value": 50}],
         "desc": "回复70%吸收量，吸收后生成一个吸收50点伤害的护盾。"},
        {"name": "吸魂盾", "level": 4, "category": "defensive", "cooldown": 14,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "absorb_and_heal", "heal_pct": 100},
                     {"type": "shield_after_absorb", "value": 100},
                     {"type": "dmg_boost_after_absorb", "value": 20, "duration": 3}],
         "desc": "回复100%吸收量，生成吸收100点护盾，并提升20%伤害持续3秒。"},
    ],
    # ---- 辅助类 (Support) ----
    "治疗术": [
        {"name": "治疗术", "level": 1, "category": "support", "cooldown": 12,
         "damage": 0, "range_desc": "15m单体",
         "effects": [{"type": "heal", "value": 30}],
         "desc": "为一名队友回复30点生命。"},
        {"name": "治疗术", "level": 2, "category": "support", "cooldown": 12,
         "damage": 0, "range_desc": "18m单体",
         "effects": [{"type": "heal", "value": 50, "self_target": True}],
         "desc": "回复50点生命，可对自己使用。"},
        {"name": "治疗术", "level": 3, "category": "support", "cooldown": 12,
         "damage": 0, "range_desc": "20m单体",
         "effects": [{"type": "heal", "value": 80, "self_target": True},
                     {"type": "cleanse", "count": 1}],
         "desc": "回复80点生命，并清除一个负面效果。"},
        {"name": "治疗术", "level": 4, "category": "support", "cooldown": 12,
         "damage": 0, "range_desc": "22m单体",
         "effects": [{"type": "heal", "value": 110, "self_target": True},
                     {"type": "cleanse_all"},
                     {"type": "overheal_shield", "pct": 30}],
         "desc": "回复110点生命，清除所有负面效果，过量治疗的30%转化为临时护盾。"},
    ],
    "加速光环": [
        {"name": "加速光环", "level": 1, "category": "support", "cooldown": 0,
         "damage": 0, "range_desc": "自身周围8m光环 (被动)",
         "effects": [{"type": "aura_speed", "value": 10, "radius": 8}],
         "desc": "自身和周围队友移动速度提升10%。"},
        {"name": "加速光环", "level": 2, "category": "support", "cooldown": 0,
         "damage": 0, "range_desc": "自身周围10m光环 (被动)",
         "effects": [{"type": "aura_speed", "value": 15, "radius": 10}],
         "desc": "提升15%，范围扩大。"},
        {"name": "加速光环", "level": 3, "category": "support", "cooldown": 0,
         "damage": 0, "range_desc": "光环 (被动+主动)",
         "effects": [{"type": "aura_speed", "value": 20},
                     {"type": "active_speed_boost", "value": 30, "duration": 3}],
         "desc": "提升20%，主动激活后3秒内提升至30%。"},
        {"name": "加速光环", "level": 4, "category": "support", "cooldown": 15,
         "damage": 0, "range_desc": "自身周围15m光环",
         "effects": [{"type": "aura_speed", "value": 30, "radius": 15},
                     {"type": "active_untargetable", "duration": 1},
                     {"type": "active_speed_boost", "value": 30, "duration": 4}],
         "desc": "提升30%，主动激活后全体获得1秒不可选中，加速持续4秒。"},
    ],
    "能量灌注": [
        {"name": "能量灌注", "level": 1, "category": "support", "cooldown": 20,
         "damage": 0, "range_desc": "15m单体",
         "effects": [{"type": "cd_reduction_pct", "value": 20, "duration": 5}],
         "desc": "为一名队友回复20%技能冷却缩减，持续5秒。"},
        {"name": "能量灌注", "level": 2, "category": "support", "cooldown": 20,
         "damage": 0, "range_desc": "18m单体",
         "effects": [{"type": "cd_reduction_pct", "value": 30, "duration": 5},
                     {"type": "instant_cd_reduction", "value": 1}],
         "desc": "回复30%，并立即减少一个技能1秒冷却。"},
        {"name": "能量灌注", "level": 3, "category": "support", "cooldown": 20,
         "damage": 0, "range_desc": "20m单体",
         "effects": [{"type": "cd_reduction_pct", "value": 40, "duration": 5},
                     {"type": "instant_cd_reduction", "value": 2},
                     {"type": "skill_cost_reduction", "value": 20, "duration": 5}],
         "desc": "回复40%，立即减少2秒冷却，持续期间技能消耗降低20%。"},
        {"name": "能量灌注", "level": 4, "category": "support", "cooldown": 20,
         "damage": 0, "range_desc": "22m单体",
         "effects": [{"type": "cd_reduction_pct", "value": 50, "duration": 5},
                     {"type": "instant_cd_reduction", "value": 3},
                     {"type": "refresh_last_skill"}],
         "desc": "回复50%，立即减少3秒冷却，并刷新一个最近使用过的技能冷却。"},
    ],
    "复活祷言": [
        {"name": "复活祷言", "level": 1, "category": "support", "cooldown": 40,
         "damage": 0, "range_desc": "标记放置10m, 救起半径5m",
         "effects": [{"type": "revive_beacon", "revive_time_reduction": 0.5, "duration": 30, "radius": 5}],
         "desc": "可在地面标记一个点，30秒内若队友在此范围内倒地，救起时间减半。"},
        {"name": "复活祷言", "level": 2, "category": "support", "cooldown": 40,
         "damage": 0, "range_desc": "标记放置12m, 救起半径6m",
         "effects": [{"type": "revive_beacon", "auto_revive": True, "revive_time": 8, "radius": 6}],
         "desc": "标记点使倒地队友自动救起，需8秒。"},
        {"name": "复活祷言", "level": 3, "category": "support", "cooldown": 40,
         "damage": 0, "range_desc": "标记放置15m, 救起半径8m",
         "effects": [{"type": "revive_beacon", "revive_hp_pct": 30, "cast_time": 8, "radius": 8}],
         "desc": "标记点使死亡的队友以30%生命复活，需8秒吟唱。"},
        {"name": "复活祷言", "level": 4, "category": "support", "cooldown": 40,
         "damage": 0, "range_desc": "标记放置18m, 救起半径10m",
         "effects": [{"type": "instant_revive", "revive_hp_pct": 60}],
         "desc": "立即复活一名倒地队友，复活后拥有60%生命。"},
    ],
    "护甲祝福": [
        {"name": "护甲祝福", "level": 1, "category": "support", "cooldown": 10,
         "damage": 0, "range_desc": "15m单体",
         "effects": [{"type": "ally_armor", "value": 10, "duration": 3},
                     {"type": "crit_reduction", "value": 10, "duration": 3}],
         "desc": "为队友增加10点护甲，持续3秒，祝福期间受到暴击伤害减10%。"},
        {"name": "护甲祝福", "level": 2, "category": "support", "cooldown": 10,
         "damage": 0, "range_desc": "18m单体",
         "effects": [{"type": "ally_armor", "value": 20, "duration": 3},
                     {"type": "ally_dmg_boost", "value": 5, "duration": 3},
                     {"type": "crit_reduction", "value": 20, "duration": 3}],
         "desc": "护甲20点，同时增加5%伤害，受到暴击伤害减20%。"},
        {"name": "护甲祝福", "level": 3, "category": "support", "cooldown": 10,
         "damage": 0, "range_desc": "20m单体",
         "effects": [{"type": "ally_armor", "value": 30, "duration": 3},
                     {"type": "ally_dmg_boost", "value": 10, "duration": 3},
                     {"type": "crit_reduction", "value": 30, "duration": 3}],
         "desc": "护甲30点，增加10%伤害，受到暴击伤害减30%。"},
        {"name": "护甲祝福", "level": 4, "category": "support", "cooldown": 10,
         "damage": 0, "range_desc": "22m单体",
         "effects": [{"type": "ally_armor", "value": 45, "duration": 3},
                     {"type": "ally_dmg_boost", "value": 15, "duration": 3},
                     {"type": "crit_reduction", "value": 50, "duration": 3}],
         "desc": "护甲45点，增加15%伤害，受到暴击伤害减50%。"},
    ],
    "净化": [
        {"name": "净化", "level": 1, "category": "support", "cooldown": 14,
         "damage": 0, "range_desc": "15m单体",
         "effects": [{"type": "cleanse", "count": 1}],
         "desc": "移除一名队友身上一个负面效果。"},
        {"name": "净化", "level": 2, "category": "support", "cooldown": 14,
         "damage": 0, "range_desc": "18m单体",
         "effects": [{"type": "cleanse_all"},
                     {"type": "heal", "value": 10}],
         "desc": "移除所有负面效果，并回复10点生命。"},
        {"name": "净化", "level": 3, "category": "support", "cooldown": 14,
         "damage": 0, "range_desc": "20m单体",
         "effects": [{"type": "cleanse_all"},
                     {"type": "heal", "value": 15},
                     {"type": "cc_immunity", "duration": 2}],
         "desc": "移除所有负面效果，回复15点生命，移除后2秒内免疫控制。"},
        {"name": "净化", "level": 4, "category": "support", "cooldown": 14,
         "damage": 0, "range_desc": "22m单体",
         "effects": [{"type": "cleanse_all"},
                     {"type": "heal", "value": 25},
                     {"type": "cc_immunity", "duration": 3}],
         "desc": "移除所有负面效果，回复25点生命，移除后3秒内免疫控制。"},
    ],
    "鼓舞": [
        {"name": "鼓舞", "level": 1, "category": "support", "cooldown": 12,
         "damage": 0, "range_desc": "15m单体",
         "effects": [{"type": "ally_dmg_boost", "value": 10, "duration": 5}],
         "desc": "提升一名队友10%伤害，持续5秒。"},
        {"name": "鼓舞", "level": 2, "category": "support", "cooldown": 12,
         "damage": 0, "range_desc": "18m单体",
         "effects": [{"type": "ally_dmg_boost", "value": 15, "duration": 6}],
         "desc": "提升15%，持续6秒。"},
        {"name": "鼓舞", "level": 3, "category": "support", "cooldown": 12,
         "damage": 0, "range_desc": "20m单体",
         "effects": [{"type": "ally_dmg_boost", "value": 20, "duration": 6},
                     {"type": "crit_rate_boost", "value": 10, "duration": 6}],
         "desc": "提升20%，持续6秒，并提升10%暴击率。"},
        {"name": "鼓舞", "level": 4, "category": "support", "cooldown": 12,
         "damage": 0, "range_desc": "22m单体",
         "effects": [{"type": "ally_dmg_boost", "value": 25, "duration": 8},
                     {"type": "kill_extends_buff", "extension": 2}],
         "desc": "提升25%，持续8秒，持续期间击杀敌人延长buff2秒。"},
    ],
    "替身傀儡": [
        {"name": "替身傀儡", "level": 1, "category": "support", "cooldown": 20,
         "damage": 0, "range_desc": "放置8m",
         "effects": [{"type": "decoy", "hp": 50}],
         "desc": "制造一个傀儡，吸引敌人攻击，傀儡有50生命值。"},
        {"name": "替身傀儡", "level": 2, "category": "support", "cooldown": 20,
         "damage": 0, "range_desc": "放置10m",
         "effects": [{"type": "decoy", "hp": 100},
                     {"type": "redirect_once"}],
         "desc": "傀儡有100生命值，存在期间可转移一次伤害给傀儡。"},
        {"name": "替身傀儡", "level": 3, "category": "support", "cooldown": 20,
         "damage": 0, "range_desc": "放置12m",
         "effects": [{"type": "decoy", "hp": 150},
                     {"type": "redirect_twice"}],
         "desc": "傀儡有150生命值，可转移两次伤害。"},
        {"name": "替身傀儡", "level": 4, "category": "support", "cooldown": 20,
         "damage": 0, "range_desc": "放置14m",
         "effects": [{"type": "decoy", "hp": 200},
                     {"type": "continuous_redirect_pct", "value": 30}],
         "desc": "傀儡有200生命值，存在期间自身受到伤害的30%转移给傀儡。"},
    ],
    "共享知觉": [
        {"name": "共享知觉", "level": 1, "category": "support", "cooldown": 30,
         "damage": 0, "range_desc": "全图共享视野",
         "effects": [{"type": "shared_vision", "duration": 10, "targets": 1}],
         "desc": "与一名队友共享视野，持续10秒。"},
        {"name": "共享知觉", "level": 2, "category": "support", "cooldown": 30,
         "damage": 0, "range_desc": "全图共享视野",
         "effects": [{"type": "shared_vision", "duration": 15, "targets": 1},
                     {"type": "mark_enemy", "count": 1}],
         "desc": "共享视野持续15秒，并标记敌方一名单位。"},
        {"name": "共享知觉", "level": 3, "category": "support", "cooldown": 30,
         "damage": 0, "range_desc": "全图共享视野",
         "effects": [{"type": "shared_vision", "duration": 20, "targets": 1},
                     {"type": "mark_enemy", "count": 2}],
         "desc": "共享视野持续20秒，标记两名敌人。"},
        {"name": "共享知觉", "level": 4, "category": "support", "cooldown": 30,
         "damage": 0, "range_desc": "全图共享视野",
         "effects": [{"type": "shared_vision", "duration": 25, "targets": 1},
                     {"type": "mark_all_enemies"}],
         "desc": "共享视野持续25秒，标记所有敌人位置。"},
    ],
    "资源转移": [
        {"name": "资源转移", "level": 1, "category": "support", "cooldown": 15,
         "damage": 0, "range_desc": "10m单体",
         "effects": [{"type": "transfer_hp", "self_pct": 20, "target_multiplier": 2}],
         "desc": "将自身20%当前生命转移给队友，转移量翻倍回复。"},
        {"name": "资源转移", "level": 2, "category": "support", "cooldown": 15,
         "damage": 0, "range_desc": "12m单体",
         "effects": [{"type": "transfer_hp", "self_pct": 30, "target_multiplier": 2},
                     {"type": "transfer_cd", "pct": 10}],
         "desc": "转移30%生命，同时转移10%冷却。"},
        {"name": "资源转移", "level": 3, "category": "support", "cooldown": 15,
         "damage": 0, "range_desc": "15m单体",
         "effects": [{"type": "transfer_hp", "self_pct": 35, "target_multiplier": 2},
                     {"type": "target_speed_boost", "value": 20, "duration": 3}],
         "desc": "转移35%生命，转移后目标获得20%加速持续3秒。"},
        {"name": "资源转移", "level": 4, "category": "support", "cooldown": 15,
         "damage": 0, "range_desc": "18m单体",
         "effects": [{"type": "transfer_hp", "self_pct": 40, "target_multiplier": 2},
                     {"type": "target_dmg_reduction", "value": 20, "duration": 3}],
         "desc": "转移40%生命，转移后目标获得20%减伤持续3秒。"},
    ],
    # ---- 控制类 (Control) ----
    "冰冻陷阱": [
        {"name": "冰冻陷阱", "level": 1, "category": "control", "cooldown": 10,
         "damage": 0, "range_desc": "放置8m, 触发半径2m",
         "effects": [{"type": "trap_freeze", "duration": 1, "delay": 1}],
         "desc": "放置一个陷阱，1秒延迟触发，触发后冰冻目标1秒。"},
        {"name": "冰冻陷阱", "level": 2, "category": "control", "cooldown": 10,
         "damage": 0, "range_desc": "放置10m, 触发半径2.5m",
         "effects": [{"type": "trap_freeze", "duration": 1.5, "invisible": True}],
         "desc": "冰冻1.5秒，陷阱隐形。"},
        {"name": "冰冻陷阱", "level": 3, "category": "control", "cooldown": 10,
         "damage": 0, "range_desc": "放置12m, 触发半径3m",
         "effects": [{"type": "trap_freeze", "duration": 2, "aoe": True}],
         "desc": "冰冻2秒，可冰冻多个敌人。"},
        {"name": "冰冻陷阱", "level": 4, "category": "control", "cooldown": 10,
         "damage": 0, "range_desc": "放置14m, 触发半径3.5m",
         "effects": [{"type": "trap_freeze", "duration": 2.5, "aoe": True},
                     {"type": "ice_ring_slow", "value": 50, "duration": 2}],
         "desc": "冰冻2.5秒，可冰冻多个敌人，触发后生成冰环减速50%持续2秒。"},
    ],
    "眩晕打击": [
        {"name": "眩晕打击", "level": 1, "category": "control", "cooldown": 10,
         "damage": 0, "range_desc": "近战3m",
         "effects": [{"type": "next_melee_stun", "duration": 0.75}],
         "desc": "下一次近战攻击眩晕0.75秒。"},
        {"name": "眩晕打击", "level": 2, "category": "control", "cooldown": 10,
         "damage": 20, "range_desc": "近战3m",
         "effects": [{"type": "next_melee_stun", "duration": 1}],
         "desc": "眩晕1秒，并造成额外20点伤害。"},
        {"name": "眩晕打击", "level": 3, "category": "control", "cooldown": 10,
         "damage": 35, "range_desc": "近战3m",
         "effects": [{"type": "next_melee_stun", "duration": 1.25},
                     {"type": "stun_vuln", "value": 10}],
         "desc": "眩晕1.25秒，额外35点伤害，眩晕期间目标受到伤害增加10%。"},
        {"name": "眩晕打击", "level": 4, "category": "control", "cooldown": 10,
         "damage": 50, "range_desc": "近战3m",
         "effects": [{"type": "next_melee_stun", "duration": 1.5},
                     {"type": "stun_vuln", "value": 20}],
         "desc": "眩晕1.5秒，额外50点伤害，眩晕期间目标受到伤害增加20%。"},
    ],
    "缠绕根须": [
        {"name": "缠绕根须", "level": 1, "category": "control", "cooldown": 10,
         "damage": 10, "range_desc": "18m单体",
         "effects": [{"type": "root", "duration": 1.5}],
         "desc": "从地下伸出根须，定身目标1.5秒，造成10点伤害。"},
        {"name": "缠绕根须", "level": 2, "category": "control", "cooldown": 10,
         "damage": 20, "range_desc": "20m单体",
         "effects": [{"type": "root", "duration": 2}],
         "desc": "定身2秒，伤害20点。"},
        {"name": "缠绕根须", "level": 3, "category": "control", "cooldown": 10,
         "damage": 30, "range_desc": "22m单体",
         "effects": [{"type": "root", "duration": 2.5},
                     {"type": "dot_while_rooted", "dps": 5}],
         "desc": "定身2.5秒，伤害30点，定身期间每秒受到5点伤害。"},
        {"name": "缠绕根须", "level": 4, "category": "control", "cooldown": 10,
         "damage": 40, "range_desc": "24m单体",
         "effects": [{"type": "root", "duration": 3},
                     {"type": "dot_while_rooted", "dps": 10},
                     {"type": "burst_on_expire", "value": 10}],
         "desc": "定身3秒，伤害40点，定身期间每秒受到10点伤害，定身结束时造成10点爆发伤害。"},
    ],
    "恐惧嚎叫": [
        {"name": "恐惧嚎叫", "level": 1, "category": "control", "cooldown": 12,
         "damage": 0, "range_desc": "前方10m扇形",
         "effects": [{"type": "fear", "duration": 0.5}],
         "desc": "对前方扇形敌人造成恐惧，使其逃离0.5秒。"},
        {"name": "恐惧嚎叫", "level": 2, "category": "control", "cooldown": 12,
         "damage": 0, "range_desc": "前方12m扇形",
         "effects": [{"type": "fear", "duration": 1}],
         "desc": "恐惧1秒，范围扩大。"},
        {"name": "恐惧嚎叫", "level": 3, "category": "control", "cooldown": 12,
         "damage": 0, "range_desc": "前方14m扇形",
         "effects": [{"type": "fear", "duration": 1.5},
                     {"type": "fear_vuln", "value": 15}],
         "desc": "恐惧1.5秒，被恐惧的目标受到伤害增加15%。"},
        {"name": "恐惧嚎叫", "level": 4, "category": "control", "cooldown": 12,
         "damage": 0, "range_desc": "前方16m扇形",
         "effects": [{"type": "fear", "duration": 2},
                     {"type": "fear_vuln", "value": 20},
                     {"type": "self_speed_boost", "value": 20, "duration": 2}],
         "desc": "恐惧2秒，受到伤害增加20%，嚎叫后自身加速20%持续2秒。"},
    ],
    "沉默领域": [
        {"name": "沉默领域", "level": 1, "category": "control", "cooldown": 14,
         "damage": 0, "range_desc": "放置12m, 半径3m",
         "effects": [{"type": "silence_zone", "duration": 2, "radius": 3}],
         "desc": "在目标区域制造沉默，持续2秒。"},
        {"name": "沉默领域", "level": 2, "category": "control", "cooldown": 14,
         "damage": 0, "range_desc": "放置14m, 半径4m",
         "effects": [{"type": "silence_zone", "duration": 3, "radius": 4}],
         "desc": "持续3秒，范围扩大。"},
        {"name": "沉默领域", "level": 3, "category": "control", "cooldown": 14,
         "damage": 0, "range_desc": "放置16m, 半径5m",
         "effects": [{"type": "silence_zone", "duration": 4, "radius": 5}],
         "desc": "持续4秒，领域内敌人无法使用技能。"},
        {"name": "沉默领域", "level": 4, "category": "control", "cooldown": 14,
         "damage": 0, "range_desc": "放置18m, 半径6m",
         "effects": [{"type": "silence_zone", "duration": 5, "radius": 6},
                     {"type": "zone_dot", "dps": 10}],
         "desc": "持续5秒，领域内敌人无法使用任何技能，并每秒受到10点伤害。"},
    ],
    "时空停滞": [
        {"name": "时空停滞", "level": 1, "category": "control", "cooldown": 20,
         "damage": 0, "range_desc": "放置15m, 半径3m",
         "effects": [{"type": "slow_zone", "value": 40, "duration": 2, "radius": 3}],
         "desc": "使目标区域时间变慢，敌人减速40%持续2秒。"},
        {"name": "时空停滞", "level": 2, "category": "control", "cooldown": 20,
         "damage": 0, "range_desc": "放置16m, 半径4m",
         "effects": [{"type": "slow_zone", "value": 60, "duration": 3, "radius": 4}],
         "desc": "减速60%，持续3秒。"},
        {"name": "时空停滞", "level": 3, "category": "control", "cooldown": 20,
         "damage": 0, "range_desc": "放置18m, 半径5m",
         "effects": [{"type": "slow_zone", "value": 80, "duration": 4, "radius": 5}],
         "desc": "减速80%，持续4秒。"},
        {"name": "时空停滞", "level": 4, "category": "control", "cooldown": 20,
         "damage": 0, "range_desc": "放置20m, 半径6m",
         "effects": [{"type": "slow_zone", "value": 90, "duration": 5, "radius": 6},
                     {"type": "projectile_slow"}],
         "desc": "减速90%，持续5秒，区域内投射物速度大幅降低。"},
    ],
    "魅惑": [
        {"name": "魅惑", "level": 1, "category": "control", "cooldown": 12,
         "damage": 0, "range_desc": "18m单体",
         "effects": [{"type": "charm", "duration": 1}],
         "desc": "使一名敌人缓慢走向施法者，持续1秒。"},
        {"name": "魅惑", "level": 2, "category": "control", "cooldown": 12,
         "damage": 0, "range_desc": "20m单体",
         "effects": [{"type": "charm", "duration": 1.5, "no_attack": True}],
         "desc": "持续1.5秒，期间目标无法攻击。"},
        {"name": "魅惑", "level": 3, "category": "control", "cooldown": 12,
         "damage": 20, "range_desc": "22m单体",
         "effects": [{"type": "charm", "duration": 2},
                     {"type": "burst_on_expire", "value": 20}],
         "desc": "持续2秒，魅惑结束时受到20点伤害。"},
        {"name": "魅惑", "level": 4, "category": "control", "cooldown": 12,
         "damage": 30, "range_desc": "24m单体",
         "effects": [{"type": "charm", "duration": 2.5},
                     {"type": "charm_vuln", "value": 20},
                     {"type": "burst_on_expire", "value": 30}],
         "desc": "持续2.5秒，魅惑期间目标受到伤害增加20%，结束时受到30点伤害。"},
    ],
    "击飞": [
        {"name": "击飞", "level": 1, "category": "control", "cooldown": 8,
         "damage": 10, "range_desc": "近战3m",
         "effects": [{"type": "airborne", "distance": 2}],
         "desc": "击飞目标，造成10点伤害并击退2米。"},
        {"name": "击飞", "level": 2, "category": "control", "cooldown": 8,
         "damage": 20, "range_desc": "近战3m",
         "effects": [{"type": "airborne", "distance": 3}],
         "desc": "伤害20点，击退3米。"},
        {"name": "击飞", "level": 3, "category": "control", "cooldown": 8,
         "damage": 30, "range_desc": "近战3m",
         "effects": [{"type": "airborne", "distance": 3},
                     {"type": "land_slow", "value": 30, "duration": 1}],
         "desc": "伤害30点，击飞后目标落地时减速30%持续1秒。"},
        {"name": "击飞", "level": 4, "category": "control", "cooldown": 8,
         "damage": 45, "range_desc": "近战3m",
         "effects": [{"type": "airborne", "distance": 4},
                     {"type": "land_stun", "duration": 0.3},
                     {"type": "land_slow", "value": 40, "duration": 1.5}],
         "desc": "伤害45点，击飞后落地眩晕0.3秒并减速40%持续1.5秒。"},
    ],
    "重力场": [
        {"name": "重力场", "level": 1, "category": "control", "cooldown": 16,
         "damage": 0, "range_desc": "放置12m, 场半径4m",
         "effects": [{"type": "gravity_pull", "duration": 2, "radius": 4}],
         "desc": "制造一个重力场，吸引周围敌人向中心缓慢移动，持续2秒。"},
        {"name": "重力场", "level": 2, "category": "control", "cooldown": 16,
         "damage": 0, "range_desc": "放置14m, 场半径5m",
         "effects": [{"type": "gravity_pull", "duration": 3, "radius": 5, "speed": "fast"}],
         "desc": "持续3秒，吸引速度加快。"},
        {"name": "重力场", "level": 3, "category": "control", "cooldown": 16,
         "damage": 0, "range_desc": "放置16m, 场半径6m",
         "effects": [{"type": "gravity_pull", "duration": 4, "radius": 6},
                     {"type": "no_displacement_in_field"}],
         "desc": "持续4秒，场内敌人无法位移。"},
        {"name": "重力场", "level": 4, "category": "control", "cooldown": 16,
         "damage": 0, "range_desc": "放置18m, 场半径7m",
         "effects": [{"type": "gravity_pull", "duration": 5, "radius": 7},
                     {"type": "center_dot", "dps": 15}],
         "desc": "持续5秒，场中心每秒造成15点伤害。"},
    ],
    "催眠曲": [
        {"name": "催眠曲", "level": 1, "category": "control", "cooldown": 13,
         "damage": 0, "range_desc": "18m单体",
         "effects": [{"type": "sleep", "duration": 2}],
         "desc": "使一名敌人进入睡眠，持续2秒，受击则醒来。"},
        {"name": "催眠曲", "level": 2, "category": "control", "cooldown": 13,
         "damage": 0, "range_desc": "20m单体",
         "effects": [{"type": "sleep", "duration": 3},
                     {"type": "wake_slow", "value": 30, "duration": 1}],
         "desc": "睡眠3秒，醒来后减速30%持续1秒。"},
        {"name": "催眠曲", "level": 3, "category": "control", "cooldown": 13,
         "damage": 0, "range_desc": "22m单体",
         "effects": [{"type": "sleep", "duration": 4},
                     {"type": "wake_slow", "value": 40, "duration": 1.5}],
         "desc": "睡眠4秒，醒来后减速40%持续1.5秒。"},
        {"name": "催眠曲", "level": 4, "category": "control", "cooldown": 13,
         "damage": 0, "range_desc": "24m单体",
         "effects": [{"type": "sleep", "duration": 5},
                     {"type": "sleep_heals_caster", "dps": 10}],
         "desc": "睡眠5秒，睡眠期间持续回复施法者生命每秒10点。"},
    ],
    # ---- 功能类 (Utility) ----
    "透视": [
        {"name": "透视", "level": 1, "category": "utility", "cooldown": 20,
         "damage": 0, "range_desc": "自身周围20m",
         "effects": [{"type": "reveal", "radius": 20, "duration": 3}],
         "desc": "显示周围20米内敌人位置，持续3秒。"},
        {"name": "透视", "level": 2, "category": "utility", "cooldown": 20,
         "damage": 0, "range_desc": "自身周围30m",
         "effects": [{"type": "reveal", "radius": 30, "duration": 5}],
         "desc": "显示范围30米，持续5秒。"},
        {"name": "透视", "level": 3, "category": "utility", "cooldown": 20,
         "damage": 0, "range_desc": "自身周围40m",
         "effects": [{"type": "reveal", "radius": 40, "duration": 7}],
         "desc": "显示范围40米，持续7秒。"},
        {"name": "透视", "level": 4, "category": "utility", "cooldown": 20,
         "damage": 0, "range_desc": "全图",
         "effects": [{"type": "reveal_all", "duration": 5}],
         "desc": "显示全图敌人位置，持续5秒。"},
    ],
    "伪装": [
        {"name": "伪装", "level": 1, "category": "utility", "cooldown": 16,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "stealth", "duration": 5, "break_on_attack": True}],
         "desc": "进入隐身状态，持续5秒，攻击或受到伤害解除隐身。"},
        {"name": "伪装", "level": 2, "category": "utility", "cooldown": 16,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "stealth", "duration": 8},
                     {"type": "stealth_speed_boost", "value": 15}],
         "desc": "持续8秒，隐身期间移速提升15%，攻击或受到伤害解除隐身。"},
        {"name": "伪装", "level": 3, "category": "utility", "cooldown": 16,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "stealth", "duration": 10},
                     {"type": "stealth_speed_boost", "value": 15},
                     {"type": "stealth_first_attack_bonus", "value": 20}],
         "desc": "持续10秒，隐身期间攻击额外造成20点伤害，攻击或受到伤害解除隐身。"},
        {"name": "伪装", "level": 4, "category": "utility", "cooldown": 16,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "stealth", "duration": 12},
                     {"type": "stealth_speed_boost", "value": 25},
                     {"type": "stealth_first_attack_bonus", "value": 30}],
         "desc": "持续12秒，隐身期间移速提升25%，攻击额外造成30点伤害，攻击或受到伤害解除隐身。"},
    ],
    "传送门": [
        {"name": "传送门", "level": 1, "category": "utility", "cooldown": 30,
         "damage": 0, "range_desc": "放置30m, 门持续10s",
         "effects": [{"type": "portal", "one_way": True, "duration": 10, "teleport_cd": 4}],
         "desc": "在脚下和目标点之间建立单向传送门，持续10秒，传送间隔4秒。"},
        {"name": "传送门", "level": 2, "category": "utility", "cooldown": 30,
         "damage": 0, "range_desc": "放置35m, 门持续15s",
         "effects": [{"type": "portal", "two_way": True, "duration": 15}],
         "desc": "双向传送门，持续15秒。"},
        {"name": "传送门", "level": 3, "category": "utility", "cooldown": 30,
         "damage": 0, "range_desc": "放置40m, 门持续20s",
         "effects": [{"type": "portal", "two_way": True, "ally_use": True, "duration": 20}],
         "desc": "传送门可被队友使用，持续20秒。"},
        {"name": "传送门", "level": 4, "category": "utility", "cooldown": 30,
         "damage": 0, "range_desc": "放置45m, 门持续25s",
         "effects": [{"type": "portal", "two_way": True, "ally_use": True, "duration": 25},
                     {"type": "speed_after_teleport", "value": 20, "duration": 4}],
         "desc": "使用传送门后获得4秒20%移速，持续25秒。"},
    ],
    "禁用": [
        {"name": "禁用", "level": 1, "category": "utility", "cooldown": 60,
         "damage": 0, "range_desc": "10m单体",
         "effects": [{"type": "disable_skill", "max_level": 1, "duration": 30}],
         "desc": "禁用目标一个1级技能（临时，持续30秒）。"},
        {"name": "禁用", "level": 2, "category": "utility", "cooldown": 60,
         "damage": 0, "range_desc": "12m单体",
         "effects": [{"type": "disable_skill", "max_level": 2, "duration": 60}],
         "desc": "禁用目标一个2级技能，偷取后持续60秒。"},
        {"name": "禁用", "level": 3, "category": "utility", "cooldown": 60,
         "damage": 0, "range_desc": "15m单体",
         "effects": [{"type": "disable_skill", "max_level": 99, "duration": 90}],
         "desc": "可禁用任意等级技能，持续90秒。"},
        {"name": "禁用", "level": 4, "category": "utility", "cooldown": 60,
         "damage": 0, "range_desc": "18m单体",
         "effects": [{"type": "disable_skill", "max_level": 99, "permanent": True}],
         "desc": "永久禁用，但对方会在死亡后掉落该技能（若原为掉落槽）。"},
    ],
    "反击姿态": [
        {"name": "反击姿态", "level": 1, "category": "utility", "cooldown": 12,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "counter_stance", "duration": 1, "counter_damage": 20}],
         "desc": "开启反击姿态，1秒内受到攻击时自动反击，对攻击者造成20点伤害。"},
        {"name": "反击姿态", "level": 2, "category": "utility", "cooldown": 12,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "counter_stance", "duration": 1, "counter_damage": 30},
                     {"type": "counter_shield", "value": 10, "duration": 2}],
         "desc": "反击伤害30点，反击后自身获得10点护盾，持续2秒。"},
        {"name": "反击姿态", "level": 3, "category": "utility", "cooldown": 12,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "counter_stance", "duration": 1, "counter_damage": 40, "interrupt": True},
                     {"type": "counter_shield", "value": 20, "duration": 2}],
         "desc": "反击伤害40点，护盾20点，且反击可打断敌人当前动作。"},
        {"name": "反击姿态", "level": 4, "category": "utility", "cooldown": 12,
         "damage": 0, "range_desc": "仅自身",
         "effects": [{"type": "counter_stance", "duration": 1, "counter_damage": 55, "interrupt": True},
                     {"type": "counter_shield", "value": 30, "duration": 2},
                     {"type": "cd_reduction_on_counter", "value": 1}],
         "desc": "反击伤害55点，护盾30点，反击成功后减少自身其他技能冷却1秒。"},
    ],
    "复制": [
        {"name": "复制", "level": 1, "category": "utility", "cooldown": 30,
         "damage": 0, "range_desc": "10m内队友",
         "effects": [{"type": "copy_skill", "max_level": 1, "permanent_this_match": True}],
         "desc": "复制一名队友的一个1级技能，持续本局。"},
        {"name": "复制", "level": 2, "category": "utility", "cooldown": 30,
         "damage": 0, "range_desc": "12m内队友",
         "effects": [{"type": "copy_skill", "max_level": 2, "synthesizable": True}],
         "desc": "可复制2级及以下技能，复制品可正常合成。"},
        {"name": "复制", "level": 3, "category": "utility", "cooldown": 30,
         "damage": 0, "range_desc": "15m内队友",
         "effects": [{"type": "copy_skill", "max_level": 99, "temporary": True}],
         "desc": "可复制任意等级技能，复制品为临时。"},
        {"name": "复制", "level": 4, "category": "utility", "cooldown": 30,
         "damage": 0, "range_desc": "18m内队友",
         "effects": [{"type": "copy_skill", "max_level": 99, "permanent": True}],
         "desc": "完美复制，复制品为永久（但占用技能槽）。"},
    ],
    "逃脱": [
        {"name": "逃脱", "level": 1, "category": "utility", "cooldown": 12,
         "damage": 0, "range_desc": "向后瞬移10m",
         "effects": [{"type": "blink_back", "distance": 10}],
         "desc": "向后瞬移10米。"},
        {"name": "逃脱", "level": 2, "category": "utility", "cooldown": 12,
         "damage": 0, "range_desc": "瞬移15m",
         "effects": [{"type": "blink_back", "distance": 15},
                     {"type": "cleanse_slow"}],
         "desc": "瞬移15米，并清除减速效果。"},
        {"name": "逃脱", "level": 3, "category": "utility", "cooldown": 12,
         "damage": 0, "range_desc": "瞬移18m",
         "effects": [{"type": "blink_back", "distance": 18},
                     {"type": "cleanse_slow"},
                     {"type": "leave_decoy"}],
         "desc": "瞬移18米，清除减速效果，并在起点留下残影迷惑敌人。"},
        {"name": "逃脱", "level": 4, "category": "utility", "cooldown": 12,
         "damage": 0, "range_desc": "瞬移至22m内指定位置",
         "effects": [{"type": "blink_targeted", "distance": 22},
                     {"type": "dmg_reduction", "value": 30, "duration": 2}],
         "desc": "瞬移至22米内指定位置，使用后2秒内受到伤害减少30%。"},
    ],
    "标记": [
        {"name": "标记", "level": 1, "category": "utility", "cooldown": 15,
         "damage": 0, "range_desc": "25m单体",
         "effects": [{"type": "mark", "duration": 10, "self_dmg_boost": 5}],
         "desc": "标记一名敌人，全队可见，持续10秒，自身对其伤害提升5%。"},
        {"name": "标记", "level": 2, "category": "utility", "cooldown": 15,
         "damage": 0, "range_desc": "30m单体",
         "effects": [{"type": "mark", "duration": 15, "self_dmg_boost": 8},
                     {"type": "mark_slow", "value": 10}],
         "desc": "持续15秒，自身伤害提升8%，被标记目标减速10%。"},
        {"name": "标记", "level": 3, "category": "utility", "cooldown": 15,
         "damage": 0, "range_desc": "35m单体",
         "effects": [{"type": "mark", "duration": 20, "self_dmg_boost": 12},
                     {"type": "mark_slow", "value": 15},
                     {"type": "mark_no_stealth"}],
         "desc": "持续20秒，自身伤害提升12%，被标记目标减速15%，且无法隐身。"},
        {"name": "标记", "level": 4, "category": "utility", "cooldown": 15,
         "damage": 0, "range_desc": "40m单体",
         "effects": [{"type": "mark", "duration": 25, "self_dmg_boost": 15},
                     {"type": "mark_slow", "value": 15},
                     {"type": "mark_no_stealth"},
                     {"type": "team_dmg_boost", "value": 8}],
         "desc": "持续25秒，自身伤害提升15%，全队对标记目标伤害提升8%，目标无法隐身。"},
    ],
    "移形换位": [
        {"name": "移形换位", "level": 1, "category": "utility", "cooldown": -1,
         "damage": 0, "range_desc": "12m内队友",
         "effects": [{"type": "swap", "radius": 12},
                     {"type": "speed_boost_both", "value": 10, "duration": 2}],
         "desc": "与一名队友瞬间互换位置。交换后双方获得10%移速加成，持续2秒。"},
        {"name": "移形换位", "level": 2, "category": "utility", "cooldown": -1,
         "damage": 0, "range_desc": "14m内队友",
         "effects": [{"type": "swap", "radius": 14},
                     {"type": "speed_boost_both", "value": 15, "duration": 2.5},
                     {"type": "cleanse_slow_self"}],
         "desc": "互换后获得15%移速加成，持续2.5秒，并清除自身减速效果。"},
        {"name": "移形换位", "level": 3, "category": "utility", "cooldown": -1,
         "damage": 0, "range_desc": "16m内队友",
         "effects": [{"type": "swap", "radius": 16},
                     {"type": "speed_boost_both", "value": 20, "duration": 3},
                     {"type": "cleanse_slow_both"},
                     {"type": "ally_shield", "value": 50}],
         "desc": "互换后获得20%移速加成，持续3秒，清除双方减速效果，并为队友提供50点临时护盾。"},
        {"name": "移形换位", "level": 4, "category": "utility", "cooldown": -1,
         "damage": 0, "range_desc": "18m内队友",
         "effects": [{"type": "swap", "radius": 18},
                     {"type": "speed_boost_both", "value": 25, "duration": 3},
                     {"type": "cleanse_all_both"},
                     {"type": "ally_shield", "value": 80},
                     {"type": "self_dmg_reduction", "value": 20, "duration": 2}],
         "desc": "互换后获得25%移速加成，持续3秒，清除双方负面效果，为队友提供80点临时护盾，自身获得20%减伤持续2秒。"},
    ],
    "洞察之眼": [
        {"name": "洞察之眼", "level": 1, "category": "utility", "cooldown": 18,
         "damage": 0, "range_desc": "25m单体",
         "effects": [{"type": "insight_mark", "duration": 5, "self_dmg_boost": 10}],
         "desc": "标记一名敌人，使其暴露视野，持续5秒，自身对该敌人伤害提升10%。"},
        {"name": "洞察之眼", "level": 2, "category": "utility", "cooldown": 18,
         "damage": 0, "range_desc": "30m单体",
         "effects": [{"type": "insight_mark", "duration": 8, "self_dmg_boost": 15},
                     {"type": "mark_slow", "value": 15}],
         "desc": "持续8秒，伤害提升15%，标记期间目标减速15%。"},
        {"name": "洞察之眼", "level": 3, "category": "utility", "cooldown": 18,
         "damage": 0, "range_desc": "35m单体",
         "effects": [{"type": "insight_mark", "duration": 10, "self_dmg_boost": 20},
                     {"type": "mark_no_stealth"}],
         "desc": "持续10秒，伤害提升20%，标记期间目标无法进入隐身。"},
        {"name": "洞察之眼", "level": 4, "category": "utility", "cooldown": 18,
         "damage": 0, "range_desc": "40m单体",
         "effects": [{"type": "insight_mark", "duration": 12, "self_dmg_boost": 25},
                     {"type": "team_vuln", "value": 10}],
         "desc": "持续12秒，伤害提升25%，标记期间目标受到的所有伤害提升10%（团队增益）。"},
    ],
}

# Flat list of all skill instances, indexed by (name, level)
def get_skill(name, level):
    """Return skill data for given name and level (1-4)."""
    skills = SKILLS.get(name)
    if skills and 1 <= level <= len(skills):
        return skills[level - 1]
    return None

def get_all_skill_names():
    """Return list of all skill names."""
    return list(SKILLS.keys())

SKILL_NAME_LIST = get_all_skill_names()
